export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  STATUS_CHANGE = 'STATUS_CHANGE',
  CHECKLIST_UPDATE = 'CHECKLIST_UPDATE',
  OBSERVATION_CREATE = 'OBSERVATION_CREATE',
  OBSERVATION_STATUS_CHANGE = 'OBSERVATION_STATUS_CHANGE',
  SUBMIT = 'SUBMIT',
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  DELIVER = 'DELIVER',
  CLOSE = 'CLOSE',
}
