export enum ChecklistStatus {
  NO_EXISTE = 'NO_EXISTE',
  PENDIENTE = 'PENDIENTE',
  EN_PRODUCCION = 'EN_PRODUCCION',
  ENTREGADO = 'ENTREGADO',
  APROBADO = 'APROBADO',
  RECHAZADO = 'RECHAZADO',
}
