export enum OperationalCheckKey {
  PLANNING_INITIAL_VALIDATED = 'PLANNING_INITIAL_VALIDATED',
  FACTORY_CONTENT_DELIVERED = 'FACTORY_CONTENT_DELIVERED',
  PLANNING_PRODUCTION_VALIDATED = 'PLANNING_PRODUCTION_VALIDATED',
  LMS_UPLOAD_COMPLETED = 'LMS_UPLOAD_COMPLETED',
  PLANNING_LMS_VALIDATED = 'PLANNING_LMS_VALIDATED',
  PRODUCT_ACADEMIC_APPROVED = 'PRODUCT_ACADEMIC_APPROVED',
  PLANNING_FINAL_RADICATED = 'PLANNING_FINAL_RADICATED',
}

export enum OperationalCheckStatus {
  PENDING = 'PENDING',
  CHECKED = 'CHECKED',
  RETURNED = 'RETURNED',
}
