export enum SemesterStatus {
  PENDING = 'PENDING',
  IN_PRODUCTION = 'IN_PRODUCTION',
  PARTIAL_REVIEW = 'PARTIAL_REVIEW',
  CHANGES_REQUESTED = 'CHANGES_REQUESTED',
  APPROVED = 'APPROVED',
  DELIVERED = 'DELIVERED',
}
