export enum SubjectOperationalState {
  NOT_STARTED = 'NOT_STARTED',
  IN_PRODUCTION = 'IN_PRODUCTION',
  IN_REVIEW = 'IN_REVIEW',
  CHANGES_REQUESTED = 'CHANGES_REQUESTED',
  CORRECTION_SENT = 'CORRECTION_SENT',
  APPROVED = 'APPROVED',
}
